### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by victoredvardsson** [LaurenceJJones/coraza-nginx-lua#1]
Hello,

Im looking for options to integrate Coraza with our openresty setup. Is this project still being maintaned or is it abandoned?

Thanks :)!

**Comment by LaurenceJJones** [comment]
This was purely a technical exploration for Coraza team and CrowdSec team. We taken this concept and applied it to our WAF integration within CrowdSec itself you find the documentation [here](https://docs.crowdsec.net/docs/next/appsec/intro)

We also support openresty as an integration by CrowdSec
